### ISSUE TITLE
Exception thrown with IFC TYPE IFCNonnegativelengthmeasure

### ISSUE THREAD

**Issue by DarthVM** [xBimTeam/Xbim.IDS.Validator#24]
After running a program with .ifc file with a class that has a type IFCNonnegativelengthmeasure, exception was thrown. 

fail: Xbim.IDS.Validator.Core.IdsModelValidator[0]
      Failed to run specification: Measure not implemented: 660
      System.NotImplementedException: Measure not implemented: 660
         at Xbim.IDS.Validator.Core.Helpers.MeasureHelpers.NormaliseUnits(IIfcValue measure, IIfcUnitAssignment units) in C:\Users\xdoyo\Desktop\Coding\Rider\IDS\IDS_EDM\Xbim.IDS.Validator.Core\Helpers\MeasureHelpers.gen.cs:line 280
         at Xbim.IDS.Validator.Core.Binders.FacetBinderBase`1.GetNormalisedValue(IIfcValue value) in C:\Users\xdoyo\Desktop\Coding\Rider\IDS\IDS_EDM\Xbim.IDS.Validator.Core\Binders\FacetBinderBase.cs:line 367
         at Xbim.IDS.Validator.Core.Binders.PsetFacetBinder.CheckProperties(IfcPropertyFacet facet, Cardinality cardinality, IdsValidationResult result, ValidationContext`1 ctx, Nullable`1& success, Nullable`1& failure, IIfcPropertySetDefinition pset, IEnumerable`1 props) in C:\Users\xdoyo\Desktop\Coding\Rider\IDS\IDS_EDM\Xbim.IDS.Validator.Core\Binders\PsetFacetBinder.cs:line 213
         at Xbim.IDS.Validator.Core.Binders.PsetFacetBinder.ValidateEntity(IPersistEntity item, IfcPropertyFacet facet, Cardinality cardinality, IdsValidationResult result) in C:\Users\xdoyo\Desktop\Coding\Rider\IDS\IDS_EDM\Xbim.IDS.Validator.Core\Binders\PsetFacetBinder.cs:line 128
         at Xbim.IDS.Validator.Core.Binders.FacetBinderBase`1.Xbim.IDS.Validator.Core.Interfaces.IFacetBinder.ValidateEntity(IPersistEntity item, IFacet facet, Cardinality cardinality, IdsValidationResult result) in C:\Users\xdoyo\Desktop\Coding\Rider\IDS\IDS_EDM\Xbim.IDS.Validator.Core\Binders\FacetBinderBase.cs:line 466
         at Xbim.IDS.Validator.Core.IdsModelBinder.ValidateRequirement(IPersistEntity item, FacetGroup requirement, ILogger logger) in C:\Users\xdoyo\Desktop\Coding\Rider\IDS\IDS_EDM\Xbim.IDS.Validator.Core\IdsModelBinder.cs:line 151
         at Xbim.IDS.Validator.Core.IdsModelValidator.ValidateRequirement(Specification spec, IModel model, ILogger userLogger, CancellationToken token) in C:\Users\xdoyo\Desktop\Coding\Rider\IDS\IDS_EDM\Xbim.IDS.Validator.Core\IdsModelValidator.cs:line 259
fail: Program[0]
      Failed to run specification: Measure not implemented: 660

![image](https://github.com/user-attachments/assets/8ae1c547-741a-4d3f-a28c-95f73d6c29ed)

![image](https://github.com/user-attachments/assets/b3c8a246-eb15-45bf-9867-7bb169033ffd)

IDS File (Guthub does not allow to upload .ids)

[IFCWALL.txt](https://github.com/user-attachments/files/16794483/IFCWALL.txt)

**Comment by andyward** [comment]
Thanks Artur

Any chance you can attach a IFC file that triggers the failure as well?

**Comment by DarthVM** [comment]
Sorry, can't upload it. File is too large.

Here is the link to Google Drive.

https://drive.google.com/file/d/1YluPuMi9Pe4DlLfQl6me9Dz61CW3C4PM/view?usp=sharing

**Comment by andyward** [comment]
Couldn't quite reproduce the issue with that model. It needed to be IFC, as IFCNONNEGATIVELENGTHMEASURE is not in IFC2x3.

Anyway, reproduced and fixed.

The issue was we attempt to normalise IfcMeasure values to the fundamental SI unit (i.e. mm, inches etc all convert to meters). But this threw when a measure was not supported. We now support more measures (including NonNegativeLength...), and log when we can't (rather than fail).

**Comment by DarthVM** [comment]
Oh, sorry. Wrong file (had it with same name in another folder). Thank you very much for resolving this issue!
